allen-cell-animated/timelapse-colorizer

index.html, src/main.ts
Problem
=======
Resolves #5 and #4
Solution
========
Steal the controls from volume-viewer, encapsulate them in a little class, and hook them up to the current redraw function
The key handler now advances time a bit more slowly but never skips a frame.
=> add full time controls

index.html, src/colorizer/ColorizeCanvas.ts, src/colorizer/Dataset.ts, src/main.ts
Problem
=======
Implements #3, add an option to fix the extremes of the range as the min/max across datasets.
Solution
========
- Adds a checkbox ('Lock Color Map Range') that locks the current min/max range values of the currently selected feature.
- Unchecking the checkbox resets the labels to the range of the currently selected feature.
- When switching datasets, the currently selected feature will remain selected unless there's no equivalent in the new dataset.
=> feat: Added checkbox for locking color map range

src/colorizer/ColorizeCanvas.ts, src/colorizer/TimeControls.ts, src/colorizer/UrlUtility.ts, src/main.ts
Problem
=======
Resolves https://github.com/allen-cell-animated/nucmorph-colorizer/issues/23!
Solution
========
- The URL of nucmorph colorizer now updates with the selected dataset, feature, frame #, and track ID.
- On initial load of the webpage, these same parameters can be pulled from the URL and used to seek to the right dataset/feature/frame/track.
- Some formatting fixes on `ColorizeCanvas.ts` are also included.
Note: There's a possible bug where approximately 25% of the time when loading invalid track IDs, the canvas will freeze on the first render and not update when clicked (even though the rest of the interface will show selected/deselected tracks and the correct timestamp). The canvas resets correctly if the time slider is changed, however. I have not been able to reproduce …
=> feature/load metadata from URL

index.html, src/colorizer/ColorizeCanvas.ts, src/main.ts
Problem
=======
Resolves [#22, Show currently hovered cell value](https://github.com/allen-cell-animated/nucmorph-colorizer/issues/22)!
Solution
========
- Adds UI text that shows the currently hovered track and feature values.
- Adds a mouse movement listener that checks the current XY of the mouse when over the canvas.
- The feature and track boxes show the value of the last hovered cell, ignoring non-cell pixels (background).
- Upon exiting the canvas, the track and feature value box resets.
https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/1b7ffade-8426-4b5b-8b21-a6d7663e537a
Questions:
- Should there be a responsive element to hovering? (should cells be highlighted? Is this too many …
=> feat: Show hovered feature values

src/colorizer/ColorizeCanvas.ts
Problem
=======
Request from @toloudis! Track paths are now hidden once the track is completed.
Solution
========
- Adjusted checks in `ColorizeCanvas.ts` for the range of the track that's visible.
=> fix: Hide track path when track completes

.prettierrc, src/App.tsx, src/colorizer/ColorizeCanvas.ts, src/colorizer/utils/data_utils.ts, src/components/FeatureThresholdPanel.tsx, src/components/LabeledRangeSlider.tsx
Problem
=======
Partially resolves action items in #124
Solution
========
- Allows thresholds on features to persist when switching datasets, even if the feature doesn't exist in the new dataset.
- Features that are not available are greyed out/disabled.
- Various improvements to formatting on the Select component in `FeatureThresholdingPanel.tsx`
- Fixed a spacing issue for selected feature names
- Replaced dropdown and search icons to be consistent with the rest of the UI
- Various improvements to Slider formatting in `LabeledRangeSlider.tsx`
- Greyed out min/max slider bound text labels when disabled. 
- Removed tooltips when disabled.
1. …
=> feat: Disabling feature thresholds

src/App.tsx, src/colorizer/ColorRamp.ts, src/colorizer/utils/data_utils.ts, src/colorizer/utils/url_utils.ts, src/components/ColorRampDropdown.module.css, src/components/ColorRampDropdown.tsx, src/components/IconButton.tsx, tests/ColorRampDropdown.test.tsx
Problem
=======
Closes #84 and #82! 
Solution
========
Adds the UI and plumbing to support reversing the color map, as well as saving to and loading the color map from the URL (and whether it's reversed).
Note that if you switch color map, the new map will not be reversed (e.g. resets when swapping maps).
- Open the link, change to a different color map, and then hit the reversal button next to the map.
- Copy the URL and paste it into a new tab. The same color map should be applied.
=> feat: Color Map reversing, URL saving

src/App.tsx, src/colorizer/ColorizeCanvas.ts, src/colorizer/Dataset.ts, src/colorizer/types.ts, src/colorizer/utils/data_utils.ts, src/colorizer/utils/url_utils.ts, src/components/CanvasWrapper.tsx, src/components/FeatureThresholdPanel.tsx, src/constants/types.ts, tests/Dataset.test.ts, tests/url_utils.test.ts
Problem
=======
Closes #124!
Solution
========
- Feature thresholds and current color ramp min+max are now saved to the URL if edited from the defaults.
- The app will now load the color ramp and thresholds from the URL on startup!
- Also refactors tests and other URL handling code to reduce assumptions about formatting in the utility scripts.
1. Open the preview link.
2. Set the feature color map range. You should see the URL update.
3. Set feature thresholds in the filters pane. You should also see the URL update.
4. Copy the URL and paste it into a new tab or browser window.
5. The thresholds + color map range should persist.
=> feat: Loading feature thresholds from URL

src/components/AppStyle.tsx, src/components/ColorRampDropdown.module.css
Problem
=======
Fixes an issue where the color map dropdown would render behind other popups. (Also fixes an issue where dropdowns would appear above modals.)
Solution
========
- Changed z-index for `ColorRampDropdown.tsx` and `Modal`.
Before:
After:
=> fix: Z-indexing issues with color ramp dropdown and modals

src/App.tsx
Problem
=======
Closes #126 
Solution
========
- Moves viewer settings to its own tab, and the Show Track Path checkbox to the top controls.
=> refactor: Moved viewer settings to tab

package-lock.json, package.json, src/App.tsx, src/assets/index.ts, src/colorizer/Collection.ts, src/colorizer/utils/url_utils.ts, src/components/LabeledDropdown.tsx, src/components/LoadDatasetButton.tsx
Problem
=======
Closes #122!
Solution
========
- Clicking on the input field in the Load menu will show a list of the 10 most recently opened datasets, with the most recent datasets at the top.
- Successfully opened datasets are saved to local storage (using the new `usehooks-ts` library), so they persist between browser sessions.
Misc:
- Adds `assets/index.ts` to start isolating some weird import syntax to a single location, specifically for SVG icon used in `LabeledDropdown`.
- Caught some typos in documentation elsewhere in the project.
- Fixes a bug where `fetchWithTimeout` would not actually time out (was able to catch this due to today's Vast outage 😋)
- Made a new issue for adding unit tests for this (#142)
Change …
=> feat: Show recent datasets in load dropdown

src/colorizer/utils/url_utils.ts, src/components/LoadDatasetButton.tsx, tests/url_utils.test.ts
Problem
=======
Closes #133!
Solution
========
- Adds a lookup table for accepted `/allen` directories, with mappings to their HTTPS equivalents.
- Updates the error messages to give more info when loading unsupported allen directories.
- Compatible with the recent datasets dropdown!
1. Open the preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-144/
2. Load this `/allen` directory: `/allen/aics/assay-dev/computational/data/EMT_deliverable_processing/LH_Analysis/Version2_ColorizerTest`
3. The dataset should appear correctly.
=> feat: Support `/allen` file links

src/App.tsx, src/colorizer/CanvasOverlay.ts, src/colorizer/ColorizeCanvas.ts, src/colorizer/Dataset.ts, src/components/CanvasWrapper.tsx
Problem
=======
Closes #61, physical time!
Solution
========
- Adds new dataset metadata parameters (start time + frame duration). The default nucmorph datasets have been updated to use these values.
- Plumbing code to pass parameters + config down to the `CanvasOverlay`.
- Rendering + formatting for the new timestamp.
- Changes the rendering pattern for `CanvasOverlay`.
- A lot of these changes needed to happen to allow the overlay elements (scale bar + timestamp) to have a transparent background beneath them. The biggest change is delaying element rendering, so that the size of the elements can be summed and a backdrop can be drawn first beneath them.
1. Open preview link …
=> feat: Physical time

src/App.tsx, src/colorizer/CanvasOverlay.ts, src/colorizer/ColorizeCanvas.ts, src/colorizer/shaders/colorize_RGBA8U.frag, src/components/CanvasWrapper.tsx
Problem
=======
Closes #135, [Include UI overlays (scale bar, time, etc.) in exported frames and video](https://github.com/allen-cell-animated/nucmorph-colorizer/issues/135)!
Solution
========
- Converts `CanvasOverlay` to an `OffscreenCanvas`, and provides the rendered canvas image as a texture to the shader.
- The shader then composites the overlay over the base image.
- Video/image export samples from the resulting `ColorizeCanvas` canvas.
1. Click the preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-156/
1. Click export, and export a video sequence of any length. Open the file.
1. The timestamp and scale bar should be visible in the exported video.
Screenshots …
=> fix: Include UI overlays in export

src/colorizer/utils/react_utils.ts, src/components/LabeledRangeSlider.tsx, src/components/tabs/FeatureThresholdsTab.tsx
Problem
=======
Fixes #134, [Incorrect range when loading thresholds not in dataset from URL](https://github.com/allen-cell-animated/nucmorph-colorizer/issues/134).
Solution
========
- LabeledRangeSlider defaults to showing a `--` label when a bound is NaN.
- Changed default feature range to `[NaN, NaN]` for features from datasets that haven't been loaded yet.
1. Open preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-157/?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Ftest%2Fcollection.json&dataset=Test%203%20Custom%20Manifest&feature=feature&filters=feature%3Atest%2520unit%3A0%3A140%2Cfeature%3A%3A35%3A140&range=35%2C140&col …
=> fix: Use placeholders for unknown bounds

.github/workflows/deploy-public-build.yml
Adds an action that triggers on pushes to main that will deploy a public build to GitHub pages.
New builds should be accessible via this link: 
https://allen-cell-animated.github.io/nucmorph-colorizer/
=> feature: GitHub pages build

.github/workflows/deploy-public-build.yml, .github/workflows/pr-preview.yml, README.md
Problem
=======
Fixes an issue where the GitHub deployment action would delete the existing PR preview files. Now, the build files are placed in a subdirectory `/main`. Also updates the resource links and adds artifacts so the build files can be inspected.
=> fix: Build and deploy GitHub action no longer deletes existing files

src/colorizer/ColorizeCanvas.ts, src/colorizer/Dataset.ts
Changes the Dataset so it loads outliers to a buffer/array that can then be read from directly.
This will let the scatterplot colorizer read which values are outliers as part of the changes for #189.
=> refactor: Changed Dataset outliers to load as a buffer instead of texture

src/colorizer/Dataset.ts, tests/Dataset.test.ts
Problem
=======
Closes #186, fixing a bug where aspect ratios would occasionally appear squashed when loading a dataset.
Solution
========
It turns out the bug was caused when the viewer was at a timestep that didn't exist in the loaded dataset. This caused the viewer to skip loading that frame. There's a frame dimension variable saved inside of the Dataset that is only updated when frames are loaded, so it would be `null` and would use an (incorrect) fallback instead.
To fix it, I forced the first frame in the dataset to load when the Dataset is open, guaranteeing that the frame dimensions will be set correctly before its data can be accessed.
(I also added unit tests to validate the new fix and test it with a few different resolutions.)
* Bug fix (non-breaking change which fixes an …
=> fix: Fixed bad aspect ratio when loading datasets

src/App.tsx, src/components/tabs/FeatureThresholdsTab.tsx
Problem
=======
Fixes a bug I found when testing the colorizer for the demo! Normally, changing the threshold for the currently selected feature will also change the color map min and max bounds. This should only happen when changing the currently selected feature's threshold, but I found that adding or removing other thresholds would also cause it to reset.
This was caused by a missing check, which was also failing because the updated threshold state was being directly mutated (rather than making a copy).
Solution
========
- Adds a check for changes to the currently selected feature threshold before resetting the min and max color map bounds.
- Edits `FeatureThresholdTab` to make copies of the array and modified thresholds before passing them to change callbacks.
* Bug fix (non-breaking …
=> fix: Fixed bug where changing a threshold would reset the color map range

src/components/tabs/FeatureThresholdsTab.tsx
Fixes a bug where filters for categorical features would not change when clicked (caused by a variable accidentally named with snake_case instead of camelCase.)
Testing: Switch to the filters view and try enabling/disabling the categories.
- Broken build: https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html?dataset=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Ftest%2F3500005828_25%2Fmanifest.json&feature=Cell%20type&filters=Cell%2520type%3A%3Afff&color=matplotlib-cool
- Fixed build: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-201/?dataset=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Ftest%2F3500005828_25%2Fmanifest.json&feature=Cell%20type&filters=Cell%2520type%3A%3Afff …
=> fix: Fixed categorical thresholds not changing on click

src/App.tsx, src/colorizer/colors/categorical_palettes.ts, src/colorizer/utils/url_utils.ts, tests/colors.test.ts, tests/url_utils.test.ts
Problem
=======
Closes #148! This is the last implementation detail for categorical features!
Solution
========
- Adds a new URL parameter for the categorical palette, and associated unit tests.
- If an existing palette was chosen, saves the palette's key (`"palette-key=adobe"`).
- If the palette is different for any color, saves the hex value of all 12 colors in the palette (`"?palette=000000-000010-000020-000030-000040-000050-000060-000070-000080-000090-0000a0-0000b0"`).
Note: I would have loved to shorten the URLs further, so I made a separate issue ticket for that: #191 
1. Open the preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-190/?dataset=https%3A%2F%2 …
=> feat: Save/load categorical palettes via URL

package-lock.json, package.json, src/App.tsx, src/colorizer/utils/math_utils.ts, src/colorizer/utils/react_utils.ts, src/components/tabs/ScatterPlotTab.tsx, src/components/tabs/scatter_plot_data_utils.ts, tests/math_utils.test.ts, tests/scatter_plot_data_utils.test.ts
Problem
=======
Closes #189, adding the color ramp coloring to the scatter plot view!
Solution
========
Plotly's existing color ramp rendering is very, very slow. To work around it, we split the color ramp gradient into many smaller colors, then take our data and sort them into many different buckets corresponding to each color. Each of these buckets can then be rendered with a single color marker, which Plotly is able to handle much faster.
This PR adds the new method `colorizeScatterPlotPoints` in `ScatterPlotTab`, which does the following steps:
1. It subsamples the current color ramp (or uses the current categorical palette).
1. It uses the feature data to sort each object into a bucket with its matching color.
1. It splits large buckets into smaller buckets (enforcing a max point …
=> feature: Colorize scatterplot

src/App.tsx
Fixed a bug where loading any feature besides the first (default) feature in a dataset via the URL would cause it to use the default feature's color map range instead. This caused odd, unexpected coloring on initial load.
Also fixes #197!
This fixes the bug by using a local variable (`newFeatureName`) to get the feature's color ramp range, rather than the `featureName` state (which may not be updated).
To test:
- Broken build (should appear in bright cyan): https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json&dataset=Mama%20Bear&feature=Height&color=matplotlib-cool
- Fixed build: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-202/?coll …
=> fix: Incorrect range when loading non-default feature from URL without range parameter

src/App.tsx
Fixes #188.
`Track.length()` returns 0 for tracks with only a single timepoint, so I substituted a check for the number of object IDs instead.
=> fix: Fixed bug where tracks with one time could not be selected

src/colorizer/ColorizeCanvas.ts, src/colorizer/Track.ts
Fixes a bug where the calculation of points for the track paths didn't take into account that some tracks could be missing segmentations for certain frames. This would cause paths to advance one or more frames ahead of where they should be.
I fixed this by using fallbacks on frames where a track did not exist, during the calculation of points in the path.
This update also adds better documentation and adjusts a few property names (`length` vs. `duration`).
Tracks with missing frames would not update their paths at the very end of the tracks due to the desync. Open the following links and advance a few frames to the very end of the selected track. In the fixed build, you should be able to see the track path update until the very last frame. (it also won't update the track path on the …
=> fix: Fixes track path desync for tracks that skipped times

src/App.tsx, src/colorizer/types.ts, src/components/LoadingSpinner.tsx, src/components/Tabs/ScatterPlotTab.tsx
Problem
=======
First step in #182, "Save Scatter Plot settings to URL (+current open tab)"
*Expected review time: small, 15-20 min*
Creates a new config object for the Scatter Plot tab, containing its current selected feature axes and the range type. This is passed into the `ScatterPlotTab`, and stored as state in the `App`.
The config object will eventually be serialized to the URL for sharing!
1. Open the preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-232/
2. Open the scatter plot tab and click around, changing various settings. Everything should still load in and work as expected.
=> feature: ScatterPlot config

src/App.tsx, src/colorizer/types.ts, src/colorizer/utils/url_utils.ts, src/components/Tabs/ScatterPlotTab.tsx, src/components/Tabs/index.ts, tests/url_utils.test.ts
Problem
=======
Closes #182! Saves the currently open tab and the scatterplot configuration to the URL.
*Expected review size: medium, ~20-30 minutes*
Solution
========
- Adds serializing and deserializing for the `ScatterPlotConfig`, allowing it to be saved and retrieved from the URL.
- Adds the currently open tab to the `ViewerConfig`, and saves it to and from the URL.
1. Open preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-233/?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json&dataset=Mama%20Bear&feature=Volume&track=602&t=123&color=matplotlib-cool&palette-key=adobe&bg-sat=100&bg-brightness=100&fg-al …
=> feature: Saving current scatterplot to the URL

src/colorizer/recorders/Mp4VideoRecorder.ts
*Estimated review size: Tiny, <5 minutes*
Updates the AVC1 video codec to actually support up to 100 MB/s, which is what the high quality video export mode is set to. (The previous version, `avc1.420032`, maxed out around 20 MB/s.)
Thanks to @interim17 for pointing this out!
=> fix: Change video codec version

src/colorizer/ColorizeCanvas.ts
Problem
=======
Fixes a warning @toloudis and I noticed yesterday, where OpenGL was warning about a zero-sized texture.
*Estimated review size: tiny, ~2 minutes*
Solution
========
- Adds a check for zero-sized textures for the `inRangeIds` data texture and skips the update if needed.
1. Open the preview link and confirm from the console that there are no OpenGL warnings: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-251/
=> fix: Fixed OpenGL warning from zero-sized texture

src/routes/LandingPage.tsx
Problem
=======
Found out that the recommended link instructions I had put as a placeholder on the landing page is actually incorrect and results in a 404 error. This is a quick patch for it!
Broken link: https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html/#/viewer
Correct link: https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html#/viewer
*Estimated size: tiny, 1 minute*
=> fix: Fixed link to work with dev build

src/Viewer.tsx
Problem
=======
Closes #254!
> When dragging the time slider, sometimes the viewport does not update until after the time slider is touched again. (May be a bug with the canvas not re-rendering after a time change, because triggering a re-render through other actions causes it to update.)
*Estimated review size: Tiny, 2 minutes*
Solution
========
- Forces re-render after frame is updated in the Viewer.
Broken build: https://dev-aics-dtp-001.int.allencell.org/nucmorph-colorizer/dist/index.html#/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fmicroscopy%2FClusterOutput%2FH2B_Deliverable_AnalysisPipelineOutput%2FH2B_Deliverable_InputImages_123Timelapses_Composite_Output%2Fcolorizer%2Fcollection.json&bg-key=png_overlay_nucobjnum
Fixed …
=> fix: View updates when going to uncached time value

package-lock.json, package.json, src/colorizer/Dataset.ts, src/colorizer/utils/dataset_utils.ts, src/colorizer/utils/type_utils.ts, tests/Dataset.test.ts
Problem
=======
Adds additional dataset metadata as part of the fix for #248.
*Estimated size: small, 15 minutes (please turn off whitespace changes)*
Solution
========
- Renames manifest versions using their semantic versioning counterparts
- Adds unit tests for loading the new metadata fields from the dataset manifest JSON file.
- Open the preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-272/#/viewer?dataset=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Ftest%2Ftest_v1.1.0%2F3500005807_1%2Fmanifest.json
- In the developer console, you should see additional metadata exported with the dataset:
=> feature: Handle v1.1.0 dataset JSON schema

src/Viewer.tsx, src/colorizer/Collection.ts, src/colorizer/utils/collection_utils.ts, tests/Collection.test.ts
Problem
=======
Closes #248 and closes #220! Updates the collection loader to handle the new v1.1.0 collection JSON schema, as described in https://github.com/allen-cell-animated/colorizer-data/pull/37, and shows the collection names (if provided) on the interface.
*Estimated size: small, 20 minutes*
Solution
========
- Adds a `collection_utils` file similar to the one that exists for datasets, which updates older legacy JSON files and updates them to the current format.
- Adds unit tests for the new collection and dataset JSON files.
1. Open this preview link and open the developer console: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-270/#/viewer?collection= …
=> feature: Handle v1.1.0 collection JSON schema

src/Viewer.tsx, src/colorizer/utils/react_utils.ts, src/components/LoadDatasetButton.tsx, src/main.tsx, src/routes/LandingPage.tsx, src/routes/index.tsx, src/types/index.tsx
Problem
=======
Closes #267, adding the load button to the landing page.
*Estimated size: small, 20 minutes*
Solution
========
This required a big refactor of the loading button! Before, it would pass out the URL and wait for the viewer to try loading it and report back whether it loaded successfully. This change moves the load into the logic for the button itself, so the loading code isn't replicated between the landing page and the viewer.
I made a lot of code moves as part of this change which I could potentially split up into smaller PRs if needed.
- Refactors LoadButton to perform the test loading step, and to pass out the loaded dataset through a callback.
- Adds the LoadButton to the landing page; loading a dataset will cause it to switch to the viewer.
- Added a nice React hook …
=> feature: Load button on landing page

.github/workflows/aws-deploy.yml
Problem
=======
This PR fixes the AWS deploy example (wherein files are uploaded to S3 and a CloudFront cache is invalidated) where there is currently an error in the `aws s3 sync ...` command. 
* [#56382596](https://github.com/orgs/AllenCellSoftware/projects/10?pane=issue&itemId=56382596)
Solution
========
This is a fairly small change set to clarify some comments and fix the `aws s3 sync ...` command. 
Change summary:
---------------
* Fix `aws s3 sync ...` command to correctly sync a directory to the S3 bucket 
* Update comments to guide future development 
Manually running the [`AWS Deploy Example` Github Actions workflow](https://github.com/allen-cell-animated/nucmorph-colorizer/actions/work …
=> Fix AWS deploy example

.github/workflows/aws-deploy.yml
Problem
=======
Updates #279 to push the build files to the S3 bucket, based on @griffinfujioka's template!
Test staging deploy is available here: https://staging.timelapse.allencell.org
Solution
========
- Adds an extra `build` job to the GitHub action, which creates the build files and saves them as an artifact.
- Updates the `deploy` job to retrieve and sync the build files to S3.
(This is how we are currently doing it for GitHub pages!)
=> feature: AWS Deployment

src/Viewer.tsx, src/colorizer/Collection.ts, src/colorizer/utils/react_utils.ts, src/components/LoadDatasetButton.tsx
Problem
=======
Closes #229, "Opening dataset from URL does not update the recent datasets dropdown in Load menu". Also makes some other fixes to the `LoadDatasetButton` and dataset loading behaviors.
*Estimated review size: small, 20 minutes*
Solution
========
I did some other refactors as part of this change, so this PR is not as focused as I would have liked to be. I tried to comment everywhere I made changes to justify my reasoning!
- The viewer page now saves loaded URLs to the recent datasets dropdown.
- Adds improved error messaging when loading datasets from the URL fails.
- Hides the dropdown if there are no recent datasets.
- Made the currently loaded dataset clickable.
* New …
=> fix: Recent datasets includes datasets loaded from URL

src/Viewer.tsx, src/colorizer/ColorizeCanvas.ts, src/colorizer/Dataset.ts, src/colorizer/Plotting.ts, src/colorizer/types.ts, src/colorizer/utils/data_utils.ts, src/colorizer/utils/dataset_utils.ts, src/colorizer/utils/url_utils.ts, src/components/PlotWrapper.tsx, src/components/Tabs/FeatureThresholdsTab.tsx, src/components/Tabs/PlotTab.tsx, src/components/Tabs/ScatterPlotTab.tsx, src/components/Tabs/scatter_plot_data_utils.ts, src/routes/LandingPageContent.ts, tests/Dataset.test.ts, tests/data_utils.test.ts, tests/url_utils.test.ts
Problem
=======
*Estimated review size: medium, 30-40 minutes. (Most of the changes are variable renames which are easy to validate. Please turn off whitespace changes as well.)*
Closes #181, refactoring the colorizer to use feature keys to separate a feature's identity from its display name.
Solution
========
- Changes Dataset to generate feature keys if none exists (see new `getKeyFromName` method in `data_utils.ts`).
- Updates Datasets to lookup features by key instead of name.
- Updates all other references to features to use keys instead of names.
- The URL will now preferentially use feature keys, but the viewer can also look up by feature name if the key is not found. (This happens on the initial URL load for the scatterplot axes, feature, and thresholds/filters.)
Future work:
- …
=> refactor: Use feature keys instead of names internally

src/components/Export.tsx, src/components/Modals/StyledModal.tsx
Problem
=======
A comment Cameron made on the previous PR (#280) inspired this change! He had suggested I add a nice wrapper component for Ant Modals to hide the dependency on `useContext(DocumentContext)`. This worked great, but it didn't handle the use of Ant's static modal API elsewhere in the codebase.
This makes the same change but this time for Ant's static modal API! I'm using the static API in a couple places (including the upcoming #289) so this will make those PRs cleaner!
*Estimated review size: small, 15-20 minutes*
Solution
========
- Adds a drop-in replacement for `App.useApp().modal` through the new hook `useStyledModal()`.
- The returned static methods wrap Ant's existing modal API, but inject a reference to a container for the modals if there isn't one provided.
- This …
=> refactor: Added styled wrapper for the static modal API

src/components/Dropdowns/AccessibleDropdown.tsx
Problem
=======
Follow-up to #294! It turns out that I did not fix the dropdown styling, and that the styled-components override and the ant override both had the same level of specificity. (It only seemed fixed because hot-reload was causing styled-components to create a new CSS class that then took precedence over the ant override.)
*Estimated review size: tiny, 2 minutes*
Solution
========
- Increased the specificity of the styled-components override by one to fix a bug where the dropdowns were using the incorrect style.
- Fixed an incorrectly used CSS variable.
1. Open the preview link. The outlined dropdowns should be using a grey color instead of a purple: …
=> fix: Fixed bug where dropdowns were using incorrect style

src/components/AppStyle.tsx
Problem
=======
Changes the theme color slightly to pass accessibility standards. 
Requested by @lynwilhelm.
| Old | New |
| --- | --- |
|  ![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/eb9caa42-db3f-42e4-a39a-1b5d7777f38c) | ![image](https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/145e1fa3-55dc-445b-af64-13f1f97c0339) |
Solution
========
- Changed theme color from #8962d3 to #8860d2.
1. Open preview link. Everything should look more or less the same. https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-328/
=> fix: Tweaked theme color slightly to pass WebAIM Contrast Checker

src/Viewer.tsx, src/components/Tabs/PlotTab.tsx
Problem
=======
Closes #316!
Solution
========
- Adds support for enter keypress to search.
- Search box stays up to date with current track number.
**Video talk-through (🔊):**
https://github.com/allen-cell-animated/nucmorph-colorizer/assets/30200665/0d5396d7-89a8-43c7-9fa9-c38e1cdf6559
=> fix: Plot tab search bar responds to enter, updates with track number

src/colorizer/ColorizeCanvas.ts, src/colorizer/shaders/colorize_RGBA8U.frag, src/components/AppStyle.tsx, src/components/CanvasWrapper.tsx
Problem
=======
Adds a grey backdrop behind the frame in the main canvas area to show where the edges of the frame are.
Solution
========
- Passes a variable down into the shader that can set the canvas background color.
- Canvas background color is now a very light grey.
1. Open PR preview and load a dataset: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-336/
2. The edge of the canvas should be grey.
=> feat: Set canvas background color

.github/workflows/deploy-public-build.yml, 404.html, README.md, package.json, src/components/Banner/index.ts, src/main.tsx, src/routes/gh_404.tsx, src/utils/gh_routing.ts, tests/gh_routing.test.ts, vite.config.js
Problem
=======
Closes #323, removing hash routing and switching to browser-based routing!
*Estimated review size: large, ~30 minutes (faster if comparing with copied files)*
Solution
========
GH pages doesn't allow us to edit the server configuration, so we have to get clever to support single-page applications. We're using a custom 404.html page that redirects to the correct root `index.html`, just like in website-3d-cell-viewer.
This time I've added in some extra checks so we can handle traffic for subdirectories (like the `pr-preview` builds).
- Changes GitHub actions to build to root (instead of using the `/main` subdirectory)
- Copies over the `gh_routing` utility methods and the 404 error HTML template from website-3d-cell-viewer.
- Edits vite configuration to build both the …
=> feature: Removed `#` from URL paths

.github/workflows/deploy-public-build.yml
Should fix a bug with the main GitHub pages deployment where the `JamesIves/github-pages-deploy-action@v4` was expecting to be run inside of a repo. Also allow the action to be run off of any branch for testing purposes.
=> fix: Fix gh-pages build

.eslintrc, CONTRIBUTING.md, env.d.ts, src/colorizer/utils/math_utils.ts, src/components/Dropdowns/HelpDropdown.tsx, src/main.tsx, tsconfig.json, vite.config.js
Problem
=======
Closes #311, updating documentation around our versioning and printing the current version number in various places in the UI.
*Estimated review size: small, <10-15 minutes*
Solution
========
- Adds constants that are included during build for the app version and time of build.
- Edits TS config to recognize these as legal env constants.
- Prints app version on startup.
- Updates the Help dropdown to include a link to the GitHub repo and the current build version.
1. Open PR preview: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-343/
2. Open the console log. You should see the new version number and the basename of the webpage (should be something like …
=> feat: Show version number

.github/workflows/deploy-public-build.yml
Fixes a bug where assets were expected at the wrong path for the new GH pages build action. 
- Open the GH page build, which was built off of this branch: https://allen-cell-animated.github.io/nucmorph-colorizer
=> fix: Fix GH pages build (again)

src/Viewer.tsx, src/components/Banner/hooks.tsx, src/constants/url.ts
Problem
=======
Closes #228, removing nucmorph as the default dataset!
*Estimated size: small, 5-10 minutes*
Solution
========
- Removes the default nucmorph dataset that was used when datasets were missing.
- Adds an info banner for when only the empty viewer page is loaded.
- Fixes a bug where the banners would be immediately cleared on page load, leading to no banners being shown.
1. Open the preview link: https://allen-cell-animated.github.io/nucmorph-colorizer/pr-preview/pr-344/#/viewer
2. You should see an empty page with the info banner at the top:
=> feat: Remove Nucmorph as the default dataset, add banner popup for missing dataset

src/components/Dropdowns/AccessibleDropdown.tsx, src/components/Tabs/FeatureThresholdsTab.tsx
Problem
=======
Closes #355, "last item in features list is partially hidden". Also fixes an extra bug in the dropdowns I found where they would close unexpectedly.
*Estimated review time: tiny, 3 minutes*
Solution
========
- Fixes a bug where the last item in the features list dropdown would be partially hidden.
- Fixes a bug where clicking on the scrollbar in certain dropdowns causes the dropdown to close.
1. Open the preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-360/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fnucmorph-apr2024%2Fcollection.json&dataset=Mama+Bear&fe …
=> fix: Obscured dropdown items, abrupt dropdown close

src/Viewer.tsx
Problem
=======
Design from Lyndsay! Adds the number of filters currently selected to the title of the Filters tab.
Prepares for the NucMorph release which will have filters included on initial load. This makes it more obvious when data is being modified in the viewport.
*Estimated review size: tiny, 2 minutes*
Solution
========
- Filters tab now includes a count of filters in parentheses.
1. Open the preview link and switch to the filters tab: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-369/viewer?dataset=https%3A%2F%2Fraw.githubusercontent.com%2Fallen-cell-animated%2Fcolorizer-data%2Fmain%2Fdocumentation%2Fexample_dataset%2Fmanifest.json&feature=continuous_feature
2. Add one or more filters. The …
=> feat: Show filter count in tab title

src/Viewer.tsx, src/components/Tabs/ScatterPlotTab.tsx, src/components/Tabs/scatter_plot_data_utils.ts
Problem
=======
Closes #357, "built-in scatterplot time feature shows as `undefined`".
*Estimated review size: Small, 5 minutes*
Solution
========
- Adds a check for the scatterplot time feature when retrieving dataset feature names.
- Fix a bug where the time feature would not be retrieved from the URL.
1. Open the PR preview link (while on VPN): https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-367/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Fcollection.json&dataset=Mama+Bear&tab=scatter_plot&scatter-x=volume&scatter-y=scatterplot_time
2. The scatterplot tab should already be open. The time feature will be selected, and should …
=> fix: Fixed tooltip and axes titles when using the scatterplot Time feature

src/Viewer.tsx, src/components/AppStyle.tsx, src/components/Dropdowns/ColorRampDropdown.tsx, src/components/Header.tsx
Problem
=======
Closes #359 and closes #358 , issues raised by Lyndsay! Also closes #352, "reverse ramp button is covered by tooltip".
*Estimated review size: Tiny, 1-5 minutes*
Solution
========
- Increases spacing between dropdowns on the top toolbar.
- Decreases height of header by shrinking logo and removing margins from text.
- Changes Z-height of tooltips to prevent them from being covered by the header.
- Adjusts color map tooltip direction so it doesn't cover over the reverse color map button.
Preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-365/
=> fix: Header and dropdown spacing, tooltip Z-height

.github/workflows/aws-deploy.yml
Problem
=======
As `nucmorph-colorizer` repo was renamed to `timelapse-colorizer` role and policy related to it were also renamed to avoid and it led to failure in github actions workflow.
Solution
========
Rename role's name 
1. Suggestions for testing:
staging: https://github.com/allen-cell-animated/timelapse-colorizer/actions/runs/9420869265
production: https://github.com/allen-cell-animated/timelapse-colorizer/actions/runs/9420943891
Thanks for contributing!
=> fix: Change role and role session name

src/Viewer.tsx, src/colorizer/Dataset.ts, src/colorizer/types.ts, src/colorizer/utils/data_utils.ts, src/colorizer/utils/dataset_utils.ts, src/colorizer/utils/url_utils.ts, src/components/Tabs/FeatureThresholdsTab.tsx, src/routes/LandingPageContent.ts, tests/Dataset.test.ts, tests/data_utils.test.ts, tests/url_utils.test.ts
Problem
=======
Closes #382, a bug where the feature units from newer datasets did not appear on the UI. This was caused by a mismatch in the key it was retrieving ("units" instead of "unit", which is the expected format based on our documentation: https://github.com/allen-cell-animated/colorizer-data/blob/main/documentation/DATA_FORMAT.md#dataset).
Solution
========
- Feature units will now be loaded with the key `unit`.
- Changed thresholds to also refer to `unit` instead of `units` for consistency.
- Older versions of the manifest will now have features remapped from `units` to `unit`.
- Updated unit tests.
1. Load these two older datasets, which use the …
=> fix: Fixed bug where units would not appear on the UI.

src/routes/ErrorPage.tsx
Problem
=======
Closes #327, giving a better error page experience.
*Estimated review size: tiny, 3 minutes*
Solution
========
- Adds a link to GitHub issues on the error page
- Adds more helpful context and next steps to error page
- Fixes error page padding issues
1. Preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-384/bad/
Before:
After:
=> feat: Update error page to match website-3d-cell-viewer

src/Viewer.tsx, src/components/AppStyle.tsx, src/components/Header.tsx, src/routes/LandingPage.tsx, src/routes/LandingPageContent.tsx, src/types/index.tsx
Problem
=======
Closes #381 ("Home or "splash" page refinement updates needed") and closes #208 ("Update landing page with new dataset URLs + descriptions").
*Estimated review size: 20 minutes (probably faster if you skip through the landing page content)*
Solution
========
- Updates links and text descriptions for the new Nucmorph manuscript datasets.
- Adjusts margins on landing page elements for consistency
- Header on viewer now opens link in new tab
1. Open the preview: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-385/
=> feat: Update landing page for NucMorph publication + styling

src/components/AppStyle.tsx, src/components/Header.tsx, src/routes/LandingPage.tsx
Problem
=======
Closes #380 and closes #354, adjusting colors on disabled inputs and adding a color when links are hovered.
*Estimated review size: tiny, 4 minutes*
Solution
========
- Adjusts Ant theme configuration to use custom disabled background color and text color.
- Adjusts Ant theme configuration to show a hover color for text links; changes default color from purple to blue.
Preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-386/
1. Open the preview link. Hover over the links in the landing page and the header.
2. Open the default dataset and switch to the Viewer settings tab. Disabled dropdowns …
=> fix: Link hover colors and disabled inputs

src/Viewer.tsx, src/components/CanvasWrapper.tsx, src/components/LoadingSpinner.tsx, src/routes/LandingPage.tsx, src/routes/LandingPageContent.tsx
Problem
=======
The nucmorph datasets are loading noticeably slowly (10-15 seconds), so this is a stopgap measure until async feature loading (see #395) can be merged.
Solution
========
- Adds a loading spinner to the main view when datasets are being loaded or switched between.
- Fixes some styling on the loading spinner based on feedback from UX.
1. Open the PR preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-396/
2. Click on the "Exploratory" dataset, which is the largest and slowest to load. You should see the loading spinner appear.
3. The loading spinner will disappear once the dataset loads.
4. Try switching …
=> feature: Loading spinner for datasets

src/routes/LandingPage.tsx
Problem
=======
Closes #405, fixing visual hierarchy + layout on landing page.
Solution
========
- Adjusts spacing on datasets to group titles and paragraph text.
- Adjusts font size on project titles.
- Fixes "In review" label alignment
1. Open the preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-410/
Before:
After:
=> fix: TFE landing page layout

src/colorizer/loaders/UrlArrayLoader.ts
Problem
=======
Fixes a bug where certain features could not be loaded from the Exploratory NucMorph dataset because of a missing cast to `Number`. 
Error Message:
```
TypeError: Cannot convert a BigInt value to a number
at Math.min (<anonymous>)
```
*Estimated review size: tiny, 3 minutes*
Solution
========
1. Open the main build. You should see a warning message about failed feature loads: https://timelapse.allencell.org/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fdan-data%2Fcolorizer%2Fdata%2Ftest%2Fparquet%2Fcollection.json&dataset=Medium+Parquet
1. Open the preview link. The warning message should not appear: …
=> fix: Fixed bug where integer Parquet feature data could not be parsed

src/components/AppStyle.tsx, src/main.tsx, src/routes/LandingPage.tsx, src/styles/cookie-banner.css
Problem
=======
Closes #338, adding the HTML snippets + styling overrides for the cookie consent button and banner.
Solution
========
- Adds CSS styling rules to the root `main.tsx`.
- Overrides the default font style and colors to improve contrast.
- Adds an HTML snippet for the cookie settings button to the project root.
1. Open the preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-418/
2. Open the main build. You should see the incorrect font in the cookie popup. https://timelapse.allencell.org
=> feature: Add and style cookie banner

src/routes/LandingPageContent.tsx
Problem
=======
Fixes a warning emitted by `validateDOMNesting` caused by nested `p` tags.
=> fix: Fixes a dom validation warning caused by nested `p` tags.

README.md, package-lock.json, package.json, src/Viewer.tsx, src/colorizer/Collection.ts, src/colorizer/Dataset.ts, src/colorizer/index.ts, src/colorizer/loaders/ILoader.ts, src/colorizer/loaders/ImageFrameLoader.ts, src/colorizer/loaders/UrlArrayLoader.ts, src/colorizer/loaders/workers/urlLoadWorker.ts, src/colorizer/types.ts, src/colorizer/utils/data_utils.ts, src/colorizer/utils/json_utils.ts, src/colorizer/utils/texture_utils.ts, src/colorizer/utils/url_utils.ts, src/components/Tabs/ScatterPlotTab.tsx, tests/Dataset.test.ts, vite.config.js
Problem
=======
Closes #416, a bug where the progress bar would be blocked when loading Parquet data. The underlying problem was that the Parquet data would all arrive at once and need to be decoded by the main thread, causing the UI to block. This change adds multithreading using workers to parallelize this step!
Here's some stats on the new load times:
| Dataset | JSON Load | Parquet Load |
| --- | --- | --- |
| Small | 4.54s | 1.38s |
| Medium | 5.25s | 1.66s |
| Large | 5.85s | 1.68s | 
*Estimated size: medium, 20-30 minutes*
Solution
========
This one ended up a tad bit bigger than I would have liked, but that's the magic of ✨TYPE WRANGLING✨! In my initial attempt at this, I found that the UI was still stalling when the workers finished because they were copying the data arrays back …
=> feature: Use multithreading when loading feature data

index.html, src/Viewer.tsx, src/colorizer/Dataset.ts, src/colorizer/utils/dataset_utils.ts, src/components/AppStyle.tsx, src/components/GlossaryPanel.tsx, src/routes/LandingPage.tsx, src/styles/utils.tsx
Fixes an issue where bolded fonts looked blurry. The root issue was that the font (Lato) was not actually being loaded from Google Fonts, and it was using a fallback font file (without bolding) instead. The browser was using a default bolding algorithm that looked bad at smaller sizes.
Before:
After:
=> fix: Fixed blurry bold text caused by Lato not loading from Google Fonts

src/colorizer/CanvasUIOverlay.ts, src/colorizer/ColorizeCanvas.ts
Problem
=======
Fixes #414, "blurry canvas overlay on zoom levels other than 100%".
*Estimated size: tiny, 5 minutes*
1. Open the base build and try zooming in on the page itself: https://timelapse.allencell.org/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fbaseline_colonies_dataset%2Fcollection.json
2. Open the new fixed build and try zooming in on the page. The scale bar and time text should no longer appear blurry: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-440/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fbaseline_ …
=> fix: Fixed bug where the canvas overlay became blurry with zoom

src/Viewer.tsx
Problem
=======
Closes #308, "arrow keys still change time when other inputs are being used."
*Estimated review size: tiny, 1-2 minutes*
1. Open TFE and open the export field. Try editing the prefix and pressing the left or right arrow keys. The timestamp will change. https://timelapse.allencell.org/
2. Repeat with fixed (!!!) preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-444/ (The timestamp should not change!)
=> fix: Arrow keys no longer advance time when focused on an input

src/Viewer.tsx, src/components/Tabs/ScatterPlotTab.tsx
Problem
=======
Closes #451, "show selected feature in scatterplot on startup".
*Estimated size: tiny, <5 minutes*
Solution
========
- If no scatterplot axes are selected when the scatter plot tab is opened for the first time, the currently selected feature is plotted against time in the scatterplot.
1. Open preview link, select a feature, and switch to the scatterplot tab. You should see that feature plotted against time. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-452/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json&t=15&filters=growth_outlier_filter%3A% …
=> feat: Scatterplot tab plots currently selected feature if no axes are selected

src/Viewer.tsx, src/colorizer/Collection.ts, src/colorizer/Dataset.ts, src/colorizer/loaders/workers/urlLoadWorker.ts, src/colorizer/recorders/Mp4VideoRecorder.ts, src/colorizer/types.ts, src/colorizer/utils/data_utils.ts, src/colorizer/utils/dataset_utils.ts, src/colorizer/utils/url_utils.ts, src/components/AppStyle.tsx, src/components/Banner/AlertBanner.tsx, src/components/CanvasWrapper.tsx, src/components/Export.tsx, src/components/LoadDatasetButton.tsx, src/components/SpinBox.module.css, src/components/SpinBox.tsx, src/components/Tabs/ScatterPlotTab.tsx, tests/Collection.test.ts, tests/Export.test.tsx
Problem
=======
Closes #411, "Show more informative errors when datasets fail to load".
This change adds additional catches for errors and adds more informative messages that can be shown to users. It also adds explicit onscreen warnings for issues that were previously only logged to the console.
*Estimated size: medium, 30 minutes*
Solution
========
- Added callbacks for errors and warnings in the Viewer which can be passed to the Collection + Dataset classes during load operations.
- Added server error handlers in file loaders for 404 errors, etc.
- Datasets can now load even when the times data is missing. (This causes the scatterplot and plot views to not work correctly.)
New warnings and errors:
- Added warnings for missing and duplicated feature and data files.
- Added explicit …
=> feature: Improved load errors

.eslintrc, .prettierrc, src/Viewer.tsx, src/colorizer/loaders/UrlArrayLoader.ts, src/colorizer/utils/data_load_utils.ts, src/colorizer/utils/json_utils.ts, src/colorizer/utils/url_utils.ts, src/colorizer/workers/SharedWorkerPool.ts, src/colorizer/workers/worker.ts, src/colorizer/workers/workers/worker.ts
Problem
=======
First step towards #456 and #423, and for improving the scatterplot performance. This change makes the worker pool more general and allows for it to be extended with new background tasks in the near future. Most of the line count is just code being moved around!
*Estimated review size: small, 10 minutes*
Solution
========
- Moved worker-related logic out of `UrlArrayLoader` and into a new class, `SharedWorkerPool`.
- Renamed `urlLoadWorker` to `worker.ts` and moved most of the loading logic into its own utils file.
- Renamed some methods to be more specific.
- Fixes to auto-import sorting rules.
1. Load any dataset from the example URL: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-458/
=> refactor: Generalize worker pool

src/Viewer.tsx, src/colorizer/Collection.ts, src/colorizer/Dataset.ts, src/components/AppStyle.tsx, src/components/Banner/AlertBanner.tsx, src/components/LoadDatasetButton.tsx, src/utils/formatting.tsx, tests/Collection.test.ts, tests/formatting.test.ts
Problem
=======
Follow up to #453 that applies some additional styling. Adds bullet point formatting and styles error message notifications.
*Estimated size: small, 10-15 minutes*
Solution
========
- Adds the new `renderStringArrayAsJsx` function which can parse string arrays into lists of `p` and `li` elements.
- Also added unit tests for the new function.
- Styled popup notifications with the same fill + outline colors as the alert banners
1. Open https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-454/ and try loading the URL `https://dev-aics-dtp-001.int.allencell.org/dan-data/colorizer/data/test/bad-data/empty-ambiguous.json`. You should see an error message with two …
=> feature: Error and alert formatting

src/components/AppStyle.tsx, src/components/Buttons/ButtonStyleLink.tsx, src/routes/LandingPage.tsx, src/styles/utils.tsx
Problem
=======
Fixes some accessibility issues with links on the landing page.
*Estimated review size: small, <5 minutes*
Solution
========
- Landing page load links no longer contain buttons, and instead copy button styling from Ant.
- All links now have some kind of baseline focus styling.
- Added underlines to the external links on the landing page.
1. Open the preview link and use the tab key to navigate around the landing page: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-457/
**Default:**
**Focus styling:**
**Load links:**
=> feature: Link styling adjustments

src/Viewer.tsx, src/components/PlotWrapper.tsx, src/components/Tabs/PlotTab.tsx
Problem
=======
Completes part 1 of #312, "improve track plot navigation." Clicking on the track plot should take you to that time point.
*Estimated size: tiny, 5 minutes*
Solution
========
- Clicking on the track plot now jumps to that time point.
1. Open the preview link and load any dataset: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-463/
2. Click on any cell to select its track.
3. From the track plot, click the line graph. You should jump to that point in the dataset.
=> feat: Clicking on track plot now jumps to that time point

.eslintrc, src/colorizer/ColorizeCanvas.ts, src/colorizer/shaders/colorize_RGBA8U.frag, src/colorizer/types.ts, src/colorizer/utils/url_utils.ts, src/components/CanvasWrapper.tsx, src/components/Dropdowns/DrawModeDropdown.tsx, src/components/Tabs/SettingsTab.tsx
Problem
=======
Closes #165, "customize outline and path colors."
*Estimated size: small, 15 minutes*
Solution
========
- Adds an option to select the outline color in the settings tab.
- Adds the outline color as a variable in the viewer state config.
- Adds saving of the outline color to and parsing from the URL.
1. Open the preview link and load a dataset. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-466/
2. Go to the viewer settings. Click on a cell in the viewport and edit the outline color. You should see it update!
3. Copy the URL and open it in a new (incognito) window. The outline color should remain the same.
=> feature: Pick border color

src/colorizer/Plotting.ts, src/components/PlotWrapper.tsx, src/components/Tabs/PlotTab.tsx, src/components/Tabs/scatter_plot_data_utils.ts
Problem
=======
Closes #312, "improve track plot navigation".
This implements part 2 of the original spec by adding in a crosshair that shows the currently-hovered value.
*Estimated review size: small, 10-15 minutes*
Solution
========
- Changed `setTime` in `Plotting` to `updateLayout`, which renders both the dotted line (representing the current time) and the crosshair.
- Added state to track the currently hovered object in the plot (in `PlotWrapper`.)
- Added a loading spinner while the current frame is being loaded in `PlotTab`.
1. Open the preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-465/
2. Open any dataset and select a track. Hover over the line. …
=> feature: Show crosshair when hovering on track

src/Viewer.tsx
Problem
=======
Closes #350, "show dataset name at the top of the page."
Solution
========
- Use dataset name as a fallback if collection has no name.
- Adds a placeholder if no name is present at all.
1. Open preview link with named collection: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-489/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Ffull-interphase_dataset%2Fcollection.json
2. Open preview link that's a direct dataset (you should see a different dataset name!): https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-489/viewer?dataset=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc- …
=> feat: Show dataset name if collection has no name in metadata

.github/workflows/pr-preview.yml
Problem
=======
Currently there's a GitHub action that builds two previews for the app, one in its public version and one for an internal version w/ experimental features. Before, both jobs were run at the same time, resulting in a race condition where the PR comment would either have the preview or the internal version randomly.
This change orders the steps so the standard, public build preview is always built last, and overrides the internal link. You can still access the internal version by adding `-internal` to a PR preview link:
- https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-490/
- https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-490/
=> fix: Make PR preview link consistent

README.md
Updates the README to make links to the `colorizer-data` package more prominent. This change is under some scheduling constraints due to ASCB and I'd like to get it in quickly!
=> doc: Updated README text

404.html, package.json
Tiny fix! Saw that the `lang="en"` tag was missing from our 404 HTML page.
=> fix: Adds language property to 404 HTML page, adds viewer build target to package.json

src/components/LoadDatasetButton.tsx
Problem
=======
Closes #487, "Pressing enter in load dialog input should activate load."
*Estimated review size: tiny, 2 minutes*
Solution
========
- Pressing enter in the input area of the load menu now initiates a load. (This does the same thing as pressing the "Load" button.)
1. Open the PR preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-506/
2. Click the load button. Paste in the following link, and then press enter. The dataset should start loading: `https://allencell.s3.amazonaws.com/aics/nuc-morph-dataset/timelapse_feature_explorer_datasets/full-interphase_dataset/collection.json`
=> fix: Pressing enter in load menu text input initiates load

src/colorizer/ColorizeCanvas.ts, src/colorizer/shaders/colorize_RGBA8U.frag
Problem
=======
Closes #187, "Outlines are inconsistently thin on high-resolution frames." 
We had an issue where the outlines were always 2 pixels wide in the dimensions of the original data. For very high-resolution images, this resulted in very thin outlines that were hard to see.
Outlines are now 2 pixels wide regardless of zoom level or image dimensions!
Solution
========
- Edge detection in the fragment shader now steps by onscreen canvas pixels instead of original frame pixels.
1. Open the preview link and zoom/interact with cells/resize the window: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-505/viewer?collection=https%3A%2F%2F …
=> fix: Selected object outline has a consistent width with zoom

src/colorizer/AnnotationData.ts, src/colorizer/utils/react_utils.ts, tests/colorizer/AnnotationData.test.ts
Problem
=======
Part 1 of 5ish for #484, annotation prototyping!
This PR implements the data model used for annotations. It syncs a pure TS class with React state using a hook to encapsulate all changes. This isn't wired up to anything yet in this PR, but will be used extensively in the next couple PRs for this feature.
Note that this change is missing track information, which means the API will change slightly in the near future.
*Estimated review size: medium, 30 minutes (line count is higher due to unit testing)*
(Also, you can see the end result of all 5 of the annotation prototype PRs here: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-498/)
Solution
========
- Adds the new `AnnotationData` class, which stores the current annotation state in the …
=> feature: Annotation data model (annotations pt. 1)

src/Viewer.tsx, src/colorizer/types.ts
Problem
=======
Part 2 of ??? for #484, prototyping annotations.
This change is a simple code move, with a little extra placeholder for the annotation tab thrown in.
*Estimated review size: small, <10 minutes*
Solution
========
- Moved tab rendering logic out of returned JSX for readability.
- Added placeholder for Annotation tab that's only visible in internal build mode.
1. Open internal preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-500/
2. Compare with regular build. The annotation tab should not appear. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-500/
=> refactor: Moved tab rendering logic (annotations pt. 2)

.github/workflows/aws-deploy.yml, .github/workflows/deploy-public-build.yml
Problem
=======
The GH pages build failed due to `upload-artifact@v3` being deprecated. This PR updates it to the most recent release (`v4.5.0`).
See https://github.com/allen-cell-animated/timelapse-colorizer/actions/runs/12695689648.
Solution
========
- Updates `upload-artifact` action to `v4.5.0`.
=> fix: Updates upload-artifact action to most recent release

.github/workflows/aws-deploy.yml, .github/workflows/deploy-public-build.yml
I updated the `upload-artifact` dependency to v4 in a previous PR to fix a deprecation warning, but I also needed to update `download-artifact` to v4 as well for compatibility.
=> fix: Updated download-artifact dependency to v4.1.8

src/Viewer.tsx, src/components/AppStyle.tsx, src/components/CanvasWrapper.tsx, src/components/IconButton.tsx, src/components/Tabs/Annotation/AnnotationModeButton.tsx, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/LabelEditControls.tsx, src/components/Tabs/AnnotationTab.tsx, src/components/Tabs/index.ts
Problem
=======
Part 3 of 5(ish) for #484, prototyping annotations! This change adds in the annotations tab for editing and viewing annotations. 
This change adds in the annotations tab, and allows users to enter into an annotation edit mode. Clicking on objects will toggle them as being labeled or unlabeled. You can add and edit labels from the tab menu.
There are a LOT of quality-of-life changes that have been omitted for the sake of line count. Changes to the cursor and additional visualization of what points are selected vs. not will be made in the next PRs, parts 4 and 5. (There's a preview of where all the PRs are headed here: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-498)
Solution
========
- Adds the `AnnotationTab` component, which allows …
=> feature: Add annotations tab and click interaction (annotations pt. 3)

src/components/Dropdowns/ColorRampDropdown.tsx, src/components/Dropdowns/SelectionDropdown.tsx, src/components/Dropdowns/StyledSelect.tsx, src/components/Dropdowns/types.ts, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/ScatterPlotTab.tsx
Problem
=======
Closes #523, "Annotation - show label color in dropdown".
This change adds a small colored dot to the dropdowns to replace the `ColorPicker` component that was previously being used to indicate label colors. This lets users see the color of all the labels in the dropdown menu when selecting them.
Solution
========
- Adds a styling configuration override in `StyledSelect`, where any data with the optional `color` property renders an extra colored pseudo-element.
- Refactors `SelectItem` into a separate `types` file and types `StyledSelect` with it.
- Adds label colors to the selection options in `AnnotationTab`.
1. Open the preview link …
=> refactor: Added color indicator to selection dropdown for annotation labels

src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/AnnotationTable.tsx
Problem
=======
Refactor to support #516, "Annotation - add track list view."
This change moves the table view in the Annotation tab into its own component, which will be reused in a few places. This has been split out from the list view PR for ease of review!
Solution
========
- Moved annotation table-related logic into a new `AnnotationTable.tsx` component.
Preview here if you want to validate: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-529
=> refactor: Moved annotation table to a separate component

src/colorizer/utils/correlation.ts, src/colorizer/workers/SharedWorkerPool.ts, src/colorizer/workers/worker.ts, tests/correlation.test.ts
Problem
=======
Part 1 of 2 for #447. 
This change adds a new worker task for calculating correlations between features in a dataset, based on work started by @toloudis. In part 2, this will be wired up to a new correlation plot tab.
*Estimated review size: small, 10-15 minutes*
Solution
========
- Adds a new `utils/correlations.ts` file containing logic for calculating the Pearson correlation coefficient from arrays of data.
- Adds a new handler to `SharedWorkerPool.ts` for asynchronously calculating the correlation coefficient matrix for features in a dataset.
=> feat: Async calculation of correlations on workers (correlations pt. 1)

src/Viewer.tsx, src/colorizer/AnnotationData.ts, src/colorizer/types.ts, src/colorizer/utils/react_utils.ts, src/components/CanvasWrapper.tsx, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/LabelEditControls.tsx, src/components/Tooltips/CanvasHoverTooltip.tsx, tests/colorizer/AnnotationData.test.ts
Problem
=======
Closes #508, "Annotation - select whole tracks".
Adds the ability to select or deselect a whole track at once when annotating!
*Estimated review size: small, 10-20 minutes*
Solution
========
- Adds a method to change label status on many object IDs at once in `AnnotationData`.
- Adds additional state to the annotation state hook to track the current selection mode (track vs. time).
- Changes the Viewer to select/deselect all IDs in a track based on the current selection mode.
- Changes cursor to a `cell` style when selecting by tracks and adds an additional tooltip.
- Changed layout of annotation tab based on feedback from Lyndsay.
1. Open the preview link: …
=> feature: Select whole tracks in annotation mode

src/Viewer.tsx, src/colorizer/Track.ts, src/colorizer/utils/data_utils.ts, src/components/Tabs/Annotation/AnnotationDisplayList.tsx, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/AnnotationTrackThumbnail.tsx, tests/data_utils.test.ts
Problem
=======
Closes #516 ("add track list view") and closes #534, "Annotation - Add range visual in list view".
This change adds an interactive thumbnail that shows what parts of a track are currently selected.
Solution
========
- Adds a new `getIntervals` method in `data_utils`, which returns continuous ranges of integers in a list.
- Also added related unit tests
- Added a `getMissingTimes` method in `Track` to return time gaps in the track.
- Added a new `AnnotationTrackThumbnail.tsx` component, which renders what sections of a track are selected using two canvas elements.
1. Open the PR preview link: …
=> feat: Added interactive thumbnails to track list view

src/components/CanvasWrapper.tsx
Problem
=======
Closes #535, "clicking on viewport should remove focus from other elements."
Solution
========
- Clicking or dragging on the canvas now blurs focus from other elements.
=> fix: Fixes bug where clicking on the canvas did not remove focus from other elements

src/components/Banner/hooks.tsx
Problem
=======
Closes #366, "Default message banner when no dataset is loaded does not appear."
Fixes a bug that was occurring in developer mode where the error banner when datasets cannot be loaded would not appear. This was caused by React running the `useEffect` that clears the banners twice, and one of the calls occurred after the error message was created. 
You can see this working in production mode here: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-571/viewer
And in developer mode by cloning and running the branch, and going to http://localhost:5173/viewer
*Estimated review size: tiny, 2 minutes*
Solution
========
- Switched from a `useEffect` to a `useMemo` since the hook did not rely on the component to be mounted, and also to bypass React running …
=> fix: Fixed alert banners not rendering on load

src/Viewer.tsx, src/colorizer/AnnotationData.ts, src/colorizer/Dataset.ts, src/colorizer/types.ts, src/colorizer/utils/hooks/index.ts, src/colorizer/utils/hooks/useShortcutKey.ts, src/colorizer/utils/react_utils.ts, src/components/CanvasWrapper.tsx, src/components/Tabs/Annotation/AnnotationDisplayList.tsx, src/components/Tabs/Annotation/LabelEditControls.tsx, src/components/Tooltips/CanvasHoverTooltip.tsx, src/components/Tooltips/HoverTooltip.tsx
Problem
=======
Part 1 of 3 for #514, "Annotation - select range of track with shortcut keys." (Also closes #531, "optimize track building in Dataset".)
Adds a range annotation mode to select a range of objects within the same track. Click a track, go to a different timepoint, and click again to label (or unlabel) all of the objects in between.
I'll be following up on this PR with a change that visualizes the affected range.
*Estimated review size: medium, 20-25 minutes*
Solution
========
- Moved annotation click handling behavior out of `Viewer.tsx` and into a new callback, `handleAnnotationClick`.
- Added a new React hook, `useShortcutKey`, which tracks whether a given key is pressed down.
- Added a new range selection mode where, when annotation editing is enabled, clicking one an …
=> feature: Select time ranges in annotation (select range pt. 1)

src/Viewer.tsx
Problem
=======
Closes #575, "cannot stop playback when frame loading is slow."
Solution
========
- Adds a check to prevent the time slider from setting the current time during playback.
- Fixes a behavior where playback would start/resume anytime the mouse was clicked and released.
- Syncs the time slider and the current frame when time playback is paused.
1. Open PR preview and load a dataset: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-577/
2. Turn on backdrops.
3. Start playback, pause playback, jump through time, click and drag the slider during time playback, etc.
Screenshots …
=> fix: Fixed bug where time playback could not be stopped

tests/Dataset.test.ts, tests/data_utils.test.ts, tests/state/ViewerState/constants.ts, tests/state/ViewerState/dataset_slice.test.ts, tests/test_utils.ts
Problem
=======
Mini-refactor to make Zustand state refactoring pt. 4 cleaner! This removes a TODO about using actual mocked `Dataset` classes.
*Estimated review size: small, <15 minutes, faster if skipping copied code*
Solution
========
- Moved utilities for making mock Dataset objects out of `Dataset.test.ts` and into shared utilities.
- Created mock dataset constants in test folder for the viewer state store.
=> refactor: Use mock Dataset in ViewerStateStore tests (state pt. 4a)

src/Viewer.tsx, src/components/CanvasWrapper.tsx, src/components/Tabs/FeatureThresholdsTab.tsx, src/components/Tabs/ScatterPlotTab.tsx, src/state/ViewerState.ts, src/state/slices/color_ramp_slice.ts, src/state/slices/threshold_slice.ts, tests/state/ViewerState/color_ramp_slice.test.ts, tests/state/ViewerState/constants.ts, tests/state/ViewerState/threshold_slice.test.ts, tests/test_utils.ts
Problem
=======
Part 5 of ??? for #492, "refactor state management."
This change moves the feature thresholds into shared viewer state.
Solution
========
- Changes the `mockDataset` test utility to allow the mock Dataset to load mock data.
- Moved feature thresholds and inRangeLUT calculation into the `useViewerStateStore`.
- Moved logic for syncing feature thresholds with Dataset and Collection into `useViewerStateStore`.
- Updated color ramp range to sync with feature thresholds.
- Added unit tests for new threshold and color ramp behavior.
1. Open the PR preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-580/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics …
=> refactor: Moved feature thresholds into viewer state (state pt. 5)

src/Viewer.tsx, src/components/CategoricalColorPicker.tsx, src/components/Tabs/FeatureThresholdsTab.tsx, src/components/Tabs/PlotTab.tsx, src/components/Tabs/SettingsTab.tsx, src/state/ViewerState.ts, src/state/slices/backdrop_slice.ts, src/state/slices/dataset_slice.ts, tests/state/ViewerState/backdrop_slice.test.ts, tests/state/ViewerState/constants.ts, tests/state/ViewerState/dataset_slice.test.ts
Problem
=======
Part 10 of (12)??? for #492, "refactor state management."
This change is pretty unexciting. It moves the `backdropKey` into the `DatasetSlice` which cleans up some dependencies. It also changes our state access to the inline selector pattern which is better for linting & detecting deprecated dependencies.
*Estimated review size: small, 10 minutes*
Solution
========
- Changed state accessors to use the inline selector pattern, removing dependence on `useShallow`.
- Moved `backdropKey` into `DatasetSlice`, allowing `DatasetSlice` to be agnostic of `BackdropSlice`.
- Added a listener for `backdropKey` in `BackdropSlice` to sync backdrop visibility.
1. Open PR preview: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-588/ …
=> refactor: Moved `backdropKey`, changed store access to use inline selector pattern (state pt. 10)

.eslintrc, src/Viewer.tsx, src/components/PlotWrapper.tsx, src/state/slices/config_slice.ts, src/state/slices/time_slice.ts, src/state/slices/vector_slice.ts, src/state/utils/data_validation.ts, src/state/utils/store_io.ts, tests/state/ViewerState/config_slice.test.ts, tests/state/ViewerState/time_slice.test.ts, tests/state/ViewerState/utils.ts, tests/state/ViewerState/vector_slice.test.ts
Problem
=======
Part 12 of (15?) for #492, "refactor state management."
This change continues the URL serialization/deserialization work for the time, config, and vector slices of state. These slices should now be loaded from the URL successfully (but won't be synced to the URL until later).
There are four more slices that need to be serialized in the next PR.
Solution
========
- Added serialization and deserialization for the TimeSlice, ConfigSlice, and VectorSlice data.
- Added utility methods for comparing store values.
- Added unit tests.
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
1. Open the preview link: …
=> refactor: Serialization/deserialization for time, config, and vector slice (state pt. 12)

src/Viewer.tsx, src/colorizer/canvas/elements/legend.ts, src/colorizer/utils/math_utils.ts, src/colorizer/utils/url_utils.ts, src/components/LabeledSlider.tsx, src/components/Tooltips/CanvasHoverTooltip.tsx, src/state/slices/backdrop_slice.ts, src/state/slices/collection_slice.ts, src/state/slices/scatterplot_slice.ts, src/state/slices/threshold_slice.ts, src/state/utils/store_io.ts, tests/math_utils.test.ts, tests/state/ViewerState/backdrop_slice.test.ts, tests/state/ViewerState/scatterplot_slice.test.ts, tests/state/ViewerState/threshold_slice.test.ts, tests/url_utils.test.ts
Problem
=======
Part 13 of ??? for #492, "refactor state management."
This change adds serialization for the remaining state slices. This means that all viewer settings are now being pulled from the URL and set in the state on initial load.
The next PR will focus on the inverse relationship, syncing state to the URL.
*Estimated review size: medium, 30-40 minutes* (it's mostly unit tests)
Solution
========
- Added serialization and deserialization for the collection, threshold, scatterplot, and backdrop slices.
- Added unit tests.
- Fix for very small values in `numberToStringDecimal`.
- Refactored unit tests in `url_utils.ts` for threshold serialization/deserialization.
1. Open the preview link. …
=> refactor: Serialization/deserialization for collection, thresholds, scatterplot, and backdrops (state pt. 13)

src/colorizer/utils/url_utils.ts, src/state/ViewerState.ts, src/state/slices/backdrop_slice.ts, src/state/slices/collection_slice.ts, src/state/slices/color_ramp_slice.ts, src/state/slices/config_slice.ts, src/state/slices/dataset_slice.ts, src/state/slices/index.ts, src/state/slices/scatterplot_slice.ts, src/state/slices/threshold_slice.ts, src/state/slices/time_slice.ts, src/state/slices/vector_slice.ts, src/state/utils/data_validation.ts, src/state/utils/store_io.ts, src/state/utils/store_utils.ts, src/types/index.tsx, tests/state/ViewerState/scatterplot_slice.test.ts, tests/state/ViewerState/utils.ts
Problem
=======
Part 14 of 15(???) for #492, "refactor state management."
OKAY WE'RE ALMOST DONE! This change does some cleanup in the organization of the slice files-- now, there's only one file that needs to be updated when new slices are added or removed!
I also added a bunch of new types to help scope what parts of the state can be serialized. This allows for the other use case of the state serialization/deserialization, where we want to take some parameters for the app and turn it into a URL, like we do on the landing page.
Solution
========
- Added versions of `encode{}` methods in `url_utils` that handle `undefined` values.
- Renamed `ViewerState` to `ViewerStore`.
- Moved imports from slices out of `ViewerState.tes` and into …
=> refactor: Reorganize slices, update serialization/deserialization (state pt. 14)

src/state/slices/time_slice.ts, tests/state/ViewerState/time_slice.test.ts
Problem
=======
Fixes a bug where the frame could be set to `NaN`, `Infinity`, or invalid timesteps.
Min clamp:
1. Open the bugged build, where I've set the time to `-15`. You'll see the incorrect value appear on the UI. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-596/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json&dataset=Small&t=-15
2. Open the fixed build. The time will be clamped to 0. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-597/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset …
=> fix: Added input validation for time slice

src/colorizer/constants.ts, src/colorizer/types.ts, src/colorizer/utils/url_utils.ts, src/components/Export.tsx, tests/Export.test.tsx
Problem
=======
Fixes a bug where two settings in the Export modal were not being synced to state and couldn't be changed.
Solution
========
- Changes `Export.tsx` to use the viewer state store.
- Updates unit tests.
- Removes unused `ViewerConfig` type.
1. Open broken build (this link may break as PRs are merged). Open the Export modal and try to disable the checkboxes (nothing will happen): https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-596/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json
2. Open the fixed build and repeat …
=> fix: Sync Export settings with state

src/components/Banner/hooks.tsx, src/utils/formatting.tsx
Problem
=======
Two super-quick fixes for AlertBanners!
Solution
========
- Removes an erroneous semicolon in AlertBanner messages.
- Fixes a bug where duplicate AlertBanners could be emitted, causing React to throw error messages about duplicate keys.
Before:
After:
=> fix: Fixes bug where AlertBanners would allow duplicate messages

src/Viewer.tsx, src/colorizer/CanvasWithOverlay.ts, src/colorizer/ColorizeCanvas.ts, src/colorizer/Dataset.ts, src/colorizer/ICanvas.ts, src/colorizer/IRenderCanvas.ts, src/colorizer/VectorField.ts, src/colorizer/utils/data_utils.ts, src/components/CanvasWrapper.tsx
Problem
=======
Part 1 of 2ish for #560, "Refactor CanvasOverlay to be its own class, make generic Canvas."
This change makes the new `IRenderCanvas`, a new interface for the `ColorizeCanvas` class. Eventually, the plan is for the new 3D canvas renderer to also implement `IRenderCanvas`. This will also make it easier to refactor `CanvasWithOverlay` in the next PR.
*Estimated review size: large, 40 minutes*
Solution
========
- Creates the new `IRenderCanvas` interface.
- Refactors `ColorizeCanvas` with the new `setParams` method, which accepts a subset of the `ViewerStoreState`.
- Removes unused setters from `CanvasWrapper.tsx`.
1. Open preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-601/
2. Change canvas settings like …
=> refactor: Make Canvas interface, simplify ColorizeCanvas API (canvas pt. 1)

src/Viewer.tsx, src/colorizer/CanvasOverlay.ts, src/colorizer/ColorizeCanvas.ts, src/colorizer/ColorizeCanvas2D.ts, src/colorizer/IRenderCanvas.ts, src/colorizer/canvas/utils.ts, src/colorizer/types.ts, src/components/CanvasWrapper.tsx
Problem
=======
CLOSES #560, "refactor CanvasOverlay to be its own class"! 
This change allows `ColorizeCanvas` to be a separate class from `CanvasOverlay`, which will let us make a new 3D canvas class for TFE 3D!
*Estimated review size: medium, 30 minutes*
Solution
========
- Moved some scaling calculations out of `ColorizeCanvas` and into a separate `utils` method, with a new `scaleInfo` property.
- Renamed `CanvasWithOverlay` to `CanvasOverlay`, and `ColorizeCanvas` to `ColorizeCanvas2D`.
- Changed `CanvasOverlay` to hold a reference to an `innerCanvas`, which it syncs parameters and rendering with.
1. Open PR preview:
2. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr- …
=> refactor: `ColorizeCanvas` as module in `CanvasOverlay` (canvas pt. 4)

src/Viewer.tsx, src/state/utils/store_utils.ts
Problem
=======
Closes #615, "URL does not update after initial load."
This fixes a bug where the URL would not be synced after initial load, and would not update until a state update was triggered. This change ensures that URL contains all current state information right after the first load.
Solution
========
- Fixed types on `makeDebouncedCallback`.
- Triggered a URL sync after the initial dataset is loaded.
1. Open the preview link here: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-623/viewer?dataset=https://raw.githubusercontent.com/allen-cell-animated/colorizer-data/refs/heads/main/documentation/getting_started_guide/example/proce …
=> fix: URL is synced after initial load

src/colorizer/colors/color_ramps.ts
Problem
=======
Closes #613, "cyclical color maps."
Some of the new simulation data coming out of ABM uses orientation as a feature. I've added a few cyclical color maps to help visualize them. I've checked with Jess and these three initial color maps were picked!
Solution
========
- Added three cyclical color ramps from Fabio Crameri: https://www.fabiocrameri.ch/cycliccolourmaps/
1. Open preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-614/viewer?dataset=https%3A%2F%2Farcade-working-bucket.s3.us-west-2.amazonaws.com%2F0tfe%2Fcrawling_agents_tfe_demo%2Fmanifest.json&feature=orientation&color=fabio_crameri-romao
2. …
=> feat: Added three cyclical color ramps 

package-lock.json, package.json, src/Viewer.tsx, src/colorizer/CanvasOverlay.ts, src/colorizer/ColorizeCanvas3D.ts, src/colorizer/Dataset.ts, src/colorizer/IRenderCanvas.ts, src/colorizer/utils/dataset_utils.ts, src/state/slices/time_slice.ts, tests/Dataset.test.ts, tests/state/ViewerState/constants.ts, tests/test_utils.ts
Problem
=======
Closes #547, "Get 3D data source from dataset," and #551, "support frame-local IDs."
This PR defines 3D dataset info and allows them to be loaded into TFE! Datasets can provide a `frames3d` parameter, which specifies the source of a 3D file (anything that can be opened by Vol-E) and some additional metadata.
When a dataset with 3D data is loaded, the TFE viewport switches to load and show the data in 3D.
Solution
========
- Updated the dataset manifest definition to support a `frames3d` object parameter, containing 3D dataset source files and metadata.
- Datasets are now expected to provide a segmentation ID column (`seg_ids`), which is used for mapping from frame data to a global index.
- OverlayCanvas now keeps its own …
=> feature: Support for 3D dataset definitions (3D MVP pt. 4b)

src/colorizer/ColorRamp.ts
Problem
=======
Closes #626, "categorical colors are incorrect after upgrading Three.js version".
(Note: static checks will be broken until a dependency in Vol-e core is merged)
Solution
========
- Parses color stops as sRGB hex values instead of directly accessing LinearSRGB values.
1. Open the preview link. Categorical colors should appear in the viewport as they do in the color pickers. https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-633/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollectio …
=> fix: Fixed categorical colors being incorrect in viewport

package-lock.json, package.json, src/Viewer.tsx, src/colorizer/CanvasOverlay.ts, src/colorizer/ColorizeCanvas2D.ts, src/colorizer/ColorizeCanvas3D.ts, src/colorizer/Dataset.ts, src/colorizer/IRenderCanvas.ts, src/colorizer/types.ts, src/colorizer/utils/data_utils.ts, src/components/CanvasWrapper.tsx, src/components/Tooltips/CanvasHoverTooltip.tsx, tests/Dataset.test.ts, tests/data_utils.test.ts
Problem
=======
Closes #630, "display datasets with arbitrary segmentation IDs". 
This change allows datasets to skip the preprocessing step for 3D volumes and virtually eliminates it for 2D images as well! It removes a lot of the assumptions we were previously making about the ordering of data, and handles edge cases caused by missing data that we were previously not addressing.
NOTE: This branch will fail unit tests until the corresponding PR in vole-core (https://github.com/allen-cell-animated/vole-core/pull/313) is merged and released.
*Estimated review size: medium, 20-30 minutes (most of line count is unit tests, comments, and whitespace)*
Solution
========
- On load, Datasets now create a lookup for every frame that maps from segmentation IDs to global indices into the feature …
=> feat: Calculate lookup tables to support arbitrary segmentation IDs (3D MVP pt. 5)

src/colorizer/ColorizeCanvas2D.ts, src/colorizer/Dataset.ts, src/colorizer/Track.ts, src/colorizer/VectorField.ts, src/colorizer/utils/math_utils.ts, src/colorizer/workers/SharedWorkerPool.ts, tests/Dataset.test.ts
Problem
=======
Closes #556, "support 3D centroids."
This change updates Dataset to store centroids with 3D coordinates instead of just 2D, and updates all of the internal logic dealing with centroids data to match.
*Estimated review size: small, 10-15 minutes*
Solution
========
- Updated `Dataset` to convert from 2D centroids to 3D centroids on load.
- Updated logic for track paths, annotation, and vectors to use 3D centroid coordinates.
- Fixed a bug in `Dataset.getCentroid` where it would return `undefined` for vectors with `0` as a component.
- Added unit tests.
1. Open PR preview: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-643/viewer?collection=https%3A%2F%2Falle …
=> feat: Support 3D centroids (3D pt. 6)

src/colorizer/canvas/elements/scaleBar.ts
Problem
=======
Tiny fix for a bug I noticed in one of the datasets Chantelle has been working with, where attempting to export the image would cause the viewer to crash.
*Estimated review size: tiny, 2-3 minutes*
1. Open broken build here (you'll need to be on VPN) and click Export. Export a single image frame. Attempting to start the export process will cause a crash. https://tfe.allencell.org/viewer?dataset=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fassay-dev%2Fusers%2FChantelle%2Fcolorizer_data%2F20241120_20X_P0%2Fcell_seg%2Fmanifest.json
2. Open the fixed build and repeat the same actions. The viewer will not crash.  https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-653 …
=> fix: Fix crash caused by `null` frame dimensions

src/colorizer/types.ts, src/colorizer/utils/url_utils.ts, src/components/LoadDatasetButton.tsx
Problem
=======
Scientists on new projects need to load internal-only datasets on TFE. This allows more internal paths to be loaded, while also updating error messaging in case a path cannot be loaded.
Solution
========
- Attempts to load any `/allen/aics` file path from the internal server.
- Updates error messaging to include reporting instructions for paths that may not be supported.
1. Open PR preview: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-660/
2. From the load menu, paste in this fake path. You should see additional error messaging guiding users to report the …
=> feat: Allow more internal paths

src/colorizer/AnnotationData.ts, src/colorizer/CanvasOverlay.ts, src/colorizer/utils/react_utils.ts, src/components/AppStyle.tsx, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/CreateLabelForm.tsx, src/components/Tabs/Annotation/LabelEditControls.tsx, tests/colorizer/AnnotationData.test.ts
Problem
=======
Closes #568, "Annotation - Open edit dialog when creating new labels."
This PR adds various improvements to the annotation label creation and editing UI. Most notably, users are prompted to add in write in a label name + choose a label color when they create a new label. This is intended to help avoid confusion about 
This change also builds a foundation towards #459, "multi-value labels". The form will be extended with additional label configuration options for different label types and behavior.
*Estimated review size: medium, 30 minutes*
Solution
========
- Updated the API for creating new labels to specify an options object.
- Added a shared form component for both creating and editing labels.
- Added a modal that appears when activating annotation edit mode for the …
=> feat: Improved label creation flow (new annotations pt. 1)

src/colorizer/AnnotationData.ts, src/colorizer/canvas/elements/annotations.ts, src/colorizer/utils/react_utils.ts, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/CreateLabelForm.tsx, src/components/Tabs/Annotation/LabelEditControls.tsx, src/components/Tooltips/CanvasHoverTooltip.tsx, tests/colorizer/AnnotationData.test.ts, tests/state/ViewerState/utils.ts
Problem
=======
Mini refactor before #459, "multi-value labels in annotations."
This change moves the label options into an object in `LabelData`. Eventually, more options will be added to control user interactions with labels as part of the multi-value label feature!
*Estimated review size: small, <10-15 minutes*
Solution
========
- Moved label name and color into an `options` object inside of the `LabelData` type.
- Updated usage of `LabelData` options.
1. Open preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-649/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json&dataset=Small&feature=volume&bg-key …
=> refactor: Changed label data to use an options object (new annotations pt. 2)

src/colorizer/AnnotationData.ts, src/colorizer/utils/react_utils.ts, src/components/Tabs/Annotation/AnnotationTab.tsx, tests/colorizer/AnnotationData.test.ts
Problem
=======
This change refactors the internals of `AnnotationData` to include values for labels! This will eventually close #459, "multi-value labels", once more UI is implemented.
Before, labels were only boolean/binary values, where an ID could be labeled or unlabeled only. Now, labeled IDs are associated with an additional string **value** which is specified when applying the labels.
I've introduced the concept of different label types, but for now only boolean labels can be chosen from the UI. Label types just inform how user interaction with the label works, but all labels behave the same internally.
*Estimated review size: medium, 20 minutes*
Solution
========
- Updated `AnnotationData` label setters to include a string `value`. An ID can only be associated with one value at a …
=> refactor: Multi-value data for labels (new annotations pt. 3)

src/components/Dropdowns/StyledSelect.tsx, src/components/Dropdowns/types.ts, src/components/Tabs/Annotation/AnnotationTab.tsx
Problem
=======
Small improvement extension off of annotations pt. 4! This adds a small indicator of a label's type to the label dropdown.
Solution
========
- Updates the `SelectItem` type to accept a single character label, which is displayed by the `StyledSelect` and `SelectionDropdown`.
- Annotation labels now change their shape + show a character label based on the type of the label.
1. Open the preview link: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview-internal/pr-664/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection …
=> feat: Show visual indicator of label type in dropdown (annotations pt. 5)

src/Viewer.module.css, src/Viewer.tsx, src/components/AppStyle.tsx
Problem
=======
Closes #675, "show annotation + correlation plot in public build."
Solution
========
- Made the correlation plot and annotation tab visible in the public-facing build of TFE.
- Slightly adjusted padding + sizing on the overflow menu ellipsis button.
- Made font in tabs slightly smaller.
1. Open PR preview. The annotation tab + correlation plot tabs should appear: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-676/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json …
=> feat: Release internal-only tabs

package-lock.json, package.json, src/Viewer.module.css, src/colorizer/CanvasOverlay.ts, src/colorizer/canvas/elements/footer.ts, src/colorizer/canvas/utils.ts, src/colorizer/recorders/Mp4VideoRecorder.ts
Problem
=======
Closes #701, "Downloaded MP4 video could not be played in Quicktime."
This change enforces even numbered sizing on the viewport canvas, which allows the AVC1 codec to be chosen more consistently by browsers. AVC1 is generally more widely supported by desktop viewers than VP9 and AV1.
*Estimated review size: tiny, 10 minutes*
Solution
========
- Updated `mp4-muxer` dependency.
- Changed the canvas to always choose the nearest even pixel dimensions.
- Edited some CSS to handle cases where the viewport is wider than its base container.
Please do this on Chrome/Safari and not on Firefox, as there's a different bug: #719
1. Open the preview link here: …
=> fix: Enforce even dimensions on canvas when exporting

src/Viewer.tsx, src/components/AppStyle.tsx, src/components/CategoricalColorPicker.tsx, src/components/Dropdowns/DropdownWithColorPicker.tsx, src/components/Dropdowns/SelectionDropdown.tsx, src/components/Dropdowns/StyledSelect.tsx, src/components/Export.tsx, src/components/Inputs/LabeledSlider.tsx, src/components/Inputs/WrappedColorPicker.tsx, src/components/SettingsContainer.tsx, src/components/SpinBox.tsx, src/components/Tabs/Annotation/AnnotationTab.tsx, src/components/Tabs/Annotation/CreateLabelForm.tsx, src/components/Tabs/Annotation/LabelEditControls.tsx, src/components/Tabs/FeatureThresholdsTab.tsx, src/components/Tabs/Settings/VectorFieldSettings.tsx, src/components/Tabs/SettingsTab.tsx, src/constants/index.ts, src/utils/color_utils.ts
Problem
=======
Closes #730, "SettingsItem should not put interactive elements inside of a label HTML tag". 
It also fixes a couple related bugs, such as:
- Click targets for inputs were wider than the inputs themselves
- ColorPicker components could not be accessed using tab navigation
- Labels were not attached to dropdowns correctly
*Estimated review size: large, ~40 minutes (please turn off whitespace changes!)*
Solution
========
- `SettingsItem` no longer wraps both label text and inputs in a `label` component (implicit labeling)
- Instead, users are expected to pass in an `htmlFor` attribute (explicit labeling)
- Updated several components (SelectDropdown, DropdownWithColorPicker, SpinBox, etc.) to accept and set an `id` prop.
- Fixed bug where inputs would have incorrect/wide click …
=> fix: Fixed use of `label` tag, accessibility improvements in settings

package-lock.json, package.json, src/colorizer/ColorizeCanvas3D.ts
Problem
=======
Closes #727 (show outline around selected cell in 3D) and closes #641 (viewport goes black when resized).
Solution
========
- Bumped `vole-core` to `v3.15.6`.
- Fixes a bug where the viewport would go black during resize.
- Changes the selected object to be visualized with an outline (instead of the color of the volume changing).
1. Open PR preview (you will need to be on VPN): https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-733/viewer?collection=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2Fusers%2Fpeyton.lee%2Ftf …
=> refactor: Updated `vole-core` to `v3.15.6`

src/colorizer/Dataset.ts, src/components/Dropdowns/SelectionDropdown.tsx, src/components/Tabs/ScatterPlotTab.tsx, src/components/Tabs/Settings/VectorFieldSettings.tsx, src/components/Tabs/SettingsTab.tsx
Problem
=======
Fixes a bug where the tooltip covered over other buttons/inputs. This change moves all tooltips to the top of a dropdown by default.
I also changed the default time feature added by TFE to be called "Time (frames)" based on feedback from a UX discussion.
1. Open preview link here: https://allen-cell-animated.github.io/timelapse-colorizer/pr-preview/pr-735/viewer?collection=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc-morph-dataset%2Ftimelapse_feature_explorer_datasets%2Fexploratory_dataset%2Fcollection.json&dataset=Small&feature=volume_at_start_of_growth&tab=scatter_plot&scatter-x=change_in_volume_in_25_minute_window&scatter-y=volume
2. Mouse over any of the onscreen dropdowns.
Screenshots …
=> refactor: Adjust default dropdown tooltip positions, time units

package-lock.json, package.json, src/Viewer.tsx, src/colorizer/Collection.ts, src/colorizer/Dataset.ts, src/colorizer/loaders/UrlArrayLoader.ts, src/colorizer/path_resolvers/FilePathResolver.ts, src/colorizer/path_resolvers/IPathResolver.ts, src/colorizer/path_resolvers/UrlPathResolver.ts, src/colorizer/path_resolvers/index.ts, src/colorizer/utils/data_load_utils.ts, src/colorizer/utils/url_utils.ts, src/colorizer/workers/worker.ts, src/components/LoadDatasetButton.tsx, tests/Dataset.test.ts, tests/colorizer/FilePathResolver.test.ts, tests/setup.ts, tests/test_utils.ts, tests/utils/data_load_utils.test.ts
Problem
=======
Part 1 of 3(?) for #747, "Load ZIP files." This first change adds support for the core ZIP parsing behavior. Additional UX and error handling behaviors will be added in a future change.
*Estimated review size: large, 30-40 minutes*
Solution
========
- Added a new option to upload a ZIP file from the load menu.
- Added the `zipToFileMap` method which unpacks the contents of a ZIP file.
- Adds a new `FilePathResolver` class, which allows a map of relative paths and files to be queried and retrieved via URL.
- `Collection` and `Dataset` can now use `FilePathResolver` in addition to the previous URL resolution behavior.
- Added unit tests.
1. Download the two example dataset ZIP …
=> feat: Load datasets from ZIP file (ZIP pt. 1)
